/**
 * BUG REPORT — Cart Feature (js/script.js)
 * 
 * Generated by Test Engineer QA — manual code review + static analysis.
 * No browser test runner available (vanilla JS project).
 * 
 * Date: 2025-01-20
 * Commit: abc12345
 */

const bugReport = {
  summary: "CRITICAL: 8 of 10 verification criteria FAIL. Cart feature is incomplete — missing core interaction logic.",
  severity: "CRITICAL",
  tests_total: 10,
  tests_passed: 2,
  tests_failed: 8,

  bugs: [
    {
      id: "BUG-001",
      criteria: "1. Add to Cart → button berubah jadi quantity control (+/-)",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Tidak ada logic untuk toggle visibility antara .add-to-cart-btn dan .add-to-quantity-btn. Kedua button dirender bersamaan di DOM, dan .add-to-quantity-btn default display:none via CSS. Tidak ada kode yang mengubah display property saat item ditambahkan ke cart.",
      root_cause: "createProductCard() membuat kedua button, tapi addToCart() hanya push ke array cart + panggil updateCartDisplay(). Tidak ada manipulasi DOM pada dessert-box yang bersangkutan.",
      file: "js/script.js",
      lines: "~60-80 (createProductCard), ~110-120 (addToCart)"
    },
    {
      id: "BUG-002",
      criteria: "2. Klik '+' → quantity naik, cart update",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Tombol plus-circle di dalam .add-to-quantity-btn TIDAK memiliki event listener. Klik tidak menghasilkan apa-apa.",
      root_cause: "Tidak ada addEventListener untuk box-icon plus-circle. Tidak ada fungsi incrementQuantity().",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-003",
      criteria: "3. Klik '-' → quantity turun; if 0 → item hilang, button kembali ke 'Add to Cart'",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Tombol minus-circle TIDAK memiliki event listener. Tidak ada logic decrement, remove-at-zero, atau toggle button visibility.",
      root_cause: "Tidak ada addEventListener untuk box-icon minus-circle. Tidak ada fungsi decrementQuantity().",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-004",
      criteria: "4. Klik 'Remove' di cart → item hilang, cart update",
      severity: "CRITICAL",
      status: "FAIL",
      description: "updateCartDisplay() membuat button Remove dengan onclick=\"removeFromCart('...')\", tapi fungsi removeFromCart() TIDAK PERNAH didefinisikan di script.js. Klik akan menghasilkan ReferenceError.",
      root_cause: "Fungsi removeFromCart() tidak ada. updateCartDisplay() memanggil fungsi yang undefined.",
      file: "js/script.js",
      lines: "~30 (onclick handler), N/A (missing function definition)"
    },
    {
      id: "BUG-005",
      criteria: "5. Klik 'Confirm Order' → modal muncul dengan list item + total",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Tombol .confirm-order-btn TIDAK memiliki event listener. Tidak ada logic pembuatan modal order confirmation sama sekali.",
      root_cause: "Tidak ada addEventListener untuk .confirm-order-btn. Tidak ada fungsi createOrderModal() atau sejenisnya.",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-006",
      criteria: "6. Klik 'Start New Order' di modal → cart kosong, modal hilang, tampilan reset",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Modal tidak pernah dibuat (BUG-005), sehingga tidak ada tombol 'Start New Order' di modal. Logic reset dari modal tidak ada.",
      root_cause: "Dependensi pada BUG-005. Tidak ada fungsi resetCart() atau clearCart().",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-007",
      criteria: "7. Klik 'Start New Order' (reset button di cart) → cart kosong, tampilan reset",
      severity: "CRITICAL",
      status: "FAIL",
      description: "Tombol .reset-order-btn ada di HTML (index.html baris ~50) tapi TIDAK memiliki event listener di script.js. Klik tidak menghasilkan apa-apa.",
      root_cause: "Tidak ada addEventListener atau onclick handler untuk .reset-order-btn.",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-008",
      criteria: "8. Empty state muncul kembali saat cart kosong",
      severity: "MODERATE",
      status: "PARTIAL",
      description: "updateCartDisplay() memiliki logic untuk menampilkan empty state saat cart.length === 0. Namun #info-cart badge TIDAK di-update (tetap menunjukkan angka lama).",
      root_cause: "updateCartDisplay() tidak menyentuh elemen #info-cart. Badge count tidak pernah di-update di mana pun dalam kode.",
      file: "js/script.js",
      lines: "~10-40 (updateCartDisplay)"
    },
    {
      id: "BUG-009",
      criteria: "9. Cart count badge (#info-cart) reflects total items",
      severity: "MODERATE",
      status: "FAIL",
      description: "Elemen #info-cart di-set ke '(0)' secara statis di HTML. Tidak ada kode yang meng-update nilainya saat cart berubah.",
      root_cause: "Tidak ada document.querySelector('#info-cart').textContent = ... di mana pun.",
      file: "js/script.js",
      lines: "N/A (missing code)"
    },
    {
      id: "BUG-010",
      criteria: "N/A — code quality",
      severity: "LOW",
      status: "FAIL",
      description: "updateCartDisplay() membuat elemen dengan document.createElement('cart-items') — ini invalid HTML tag. Seharusnya 'div' atau 'li'. Browser mungkin me-render-nya tapi tidak sesuai standar dan bisa menyebabkan masalah styling/accessibility.",
      root_cause: "Typo: 'cart-items' (dengan dash) digunakan sebagai argument createElement, bukan sebagai class.",
      file: "js/script.js",
      line: "~25"
    }
  ],

  missing_features: [
    "Fungsi toggle button visibility (Add to Cart ↔ Quantity Control) per dessert-box",
    "Event listener untuk increment quantity (plus-circle)",
    "Event listener untuk decrement quantity (minus-circle) + remove-at-zero logic",
    "Fungsi removeFromCart(name)",
    "Event listener untuk Confirm Order + modal creation",
    "Event listener untuk Start New Order (reset button di cart)",
    "Fungsi resetCart() / clearCart()",
    "Update #info-cart badge count",
    "Fungsi untuk mengembalikan tampilan dessert-box ke 'Add to Cart' state"
  ],

  what_works: [
    "Fetch data.json dan render product cards (createProductCard)",
    "Add to Cart button menambahkan item ke array cart (addToCart)",
    "updateCartDisplay() merender ulang cart items dengan total",
    "Empty state detection di updateCartDisplay() (cart.length === 0)",
    "Infinite scroll / lazy load produk (loadMoreProducts + scroll handler)"
  ]
};

console.log(JSON.stringify(bugReport, null, 2));
